/**
 * Integration tests for the proof-pack SERVICE (Task C1). The repository hits a
 * real LOCAL Postgres (kason_hub_test); STORAGE is mocked so a deterministic set
 * of bill bytes (a real 1-page PDF, a real 1x1 PNG, and a "missing" key) drives the
 * merge without a real Supabase bucket. Skipped by default in `npx vitest run`. Run:
 *   RUN_INTEGRATION=1 \
 *     DATABASE_URL="postgresql://yonghongtan@localhost:5432/kason_hub_test" \
 *     npx vitest run src/modules/owner-billing/__tests__/proof-pack.service.test.ts
 *
 * The proof pack is the SEPARATE downloadable evidence bundle: one merged PDF of a
 * single (owner, month, apartment)'s bills — apartment-scoped (APT_B with no proofs
 * → null) and miss-resilient (a bill whose bytes are gone is SKIPPED, never throws).
 */
import { describe, it, expect, beforeEach, afterAll, vi } from "vitest";

// Storage mocked: fetchStorageBuffer resolves per-key bill bytes (or null on miss).
// The proof-pack service never calls requireBucket — only fetchStorageBuffer.
vi.mock("../../../lib/storage", () => ({
  fetchStorageBuffer: vi.fn(),
}));

import { getDb } from "@kason/db";
import { PDFDocument } from "pdf-lib";
import { fetchStorageBuffer } from "../../../lib/storage";
import { buildProofPackPdf } from "../proof-pack.service";

const RUN = process.env.RUN_INTEGRATION === "1";
const dn = RUN ? describe : describe.skip;

// Hard safety: integration runs must only ever hit a local postgres.
if (RUN) {
  const host = new URL(process.env.DATABASE_URL ?? "").hostname;
  if (host !== "localhost" && host !== "127.0.0.1") {
    throw new Error(`Refusing to run integration tests against non-local DB host: ${host}`);
  }
}

// Fixed UUIDs — disjoint from every other integration test's constants.
const ORG = "0e000000-0000-4000-8000-000000001001";
const OWNER = "0e000000-0000-4000-8000-000000001004";
const APT_A = "0e000000-0000-4000-8000-0000000010c1";
const APT_B = "0e000000-0000-4000-8000-0000000010c2";
const UPLOADER = "0e000000-0000-4000-8000-000000001002";

const MONTH = "2026-06";
const JUNE = new Date(Date.UTC(2026, 5, 1));
const ctx = { orgId: ORG, actorUserId: UPLOADER, actorRole: "admin" as const };

// A real, minimal 1x1 transparent PNG — pdf-lib's embedPng parses it.
const PNG_1x1 = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
  "base64",
);

/** A real 1-page PDF (generated by pdf-lib — guaranteed loadable). */
async function onePagePdf(): Promise<Buffer> {
  const d = await PDFDocument.create();
  d.addPage([200, 200]);
  return Buffer.from(await d.save());
}

async function seedOrg() {
  await getDb().organization.create({
    data: {
      id: ORG,
      name: "Proof-Pack Org",
      slug: "proof-pack-org",
      status: "active",
      defaultCurrency: "MYR",
      timezone: "Asia/Kuala_Lumpur",
      locale: "en-MY",
      subscriptionPlan: "free",
    },
  });
}

async function cleanup() {
  const db = getDb();
  await db.ownerExpenseProof.deleteMany({ where: { organizationId: ORG } });
  await db.organization.deleteMany({ where: { id: ORG } });
}

async function seedProof(opts: {
  apartmentId: string | null;
  category: string;
  storageKey: string;
  filename: string;
}) {
  await getDb().ownerExpenseProof.create({
    data: {
      organizationId: ORG,
      ownerPartyId: OWNER,
      statementMonth: JUNE,
      apartmentId: opts.apartmentId,
      category: opts.category,
      storageKey: opts.storageKey,
      filename: opts.filename,
      uploadedById: UPLOADER,
    },
  });
}

beforeEach(async () => {
  vi.clearAllMocks();
  await cleanup();
  await seedOrg();
});

afterAll(async () => {
  await cleanup();
});

dn("buildProofPackPdf (integration)", () => {
  it("merges one PDF + one PNG bill → valid PDF bytes, page-count ≥ 2", async () => {
    const pdf = await onePagePdf();
    await seedProof({ apartmentId: APT_A, category: "utilities_tnb", storageKey: "k/tnb.pdf", filename: "tnb.pdf" });
    await seedProof({ apartmentId: APT_A, category: "water", storageKey: "k/water.png", filename: "water.png" });
    vi.mocked(fetchStorageBuffer).mockImplementation(async (key: string) =>
      key === "k/tnb.pdf" ? pdf : key === "k/water.png" ? PNG_1x1 : null,
    );

    const bytes = await buildProofPackPdf(ctx, OWNER, MONTH, APT_A);
    expect(bytes).not.toBeNull();
    // It is a real PDF stream...
    expect(Buffer.from(bytes!).subarray(0, 4).toString("latin1")).toBe("%PDF");
    // ...with both bills: the PDF's page + the PNG's embedded page.
    const reloaded = await PDFDocument.load(bytes!);
    expect(reloaded.getPageCount()).toBeGreaterThanOrEqual(2);
  });

  it("SKIPS a bill whose fetchStorageBuffer returns null (degrade, not throw)", async () => {
    const pdf = await onePagePdf();
    await seedProof({ apartmentId: APT_A, category: "utilities_tnb", storageKey: "k/tnb.pdf", filename: "tnb.pdf" });
    await seedProof({ apartmentId: APT_A, category: "water", storageKey: "k/water.png", filename: "water.png" });
    await seedProof({ apartmentId: APT_A, category: "wifi", storageKey: "k/gone.pdf", filename: "gone.pdf" });
    // The "gone" key resolves to null → must be skipped, not abort the whole pack.
    vi.mocked(fetchStorageBuffer).mockImplementation(async (key: string) =>
      key === "k/tnb.pdf" ? pdf : key === "k/water.png" ? PNG_1x1 : null,
    );

    const bytes = await buildProofPackPdf(ctx, OWNER, MONTH, APT_A);
    expect(bytes).not.toBeNull();
    const reloaded = await PDFDocument.load(bytes!);
    // Exactly the two present bills — the missing one is dropped, not errored.
    expect(reloaded.getPageCount()).toBe(2);
  });

  it("returns null when the (owner, month, apartment) has NO proofs (→ route 404)", async () => {
    const bytes = await buildProofPackPdf(ctx, OWNER, MONTH, APT_A);
    expect(bytes).toBeNull();
    // No rows → never touches storage.
    expect(fetchStorageBuffer).not.toHaveBeenCalled();
  });

  it("APT_B (proofs only on APT_A) → null — apartment-scoped (→ route 404)", async () => {
    await seedProof({ apartmentId: APT_A, category: "utilities_tnb", storageKey: "k/tnb.pdf", filename: "tnb.pdf" });
    const bytes = await buildProofPackPdf(ctx, OWNER, MONTH, APT_B);
    expect(bytes).toBeNull();
    expect(fetchStorageBuffer).not.toHaveBeenCalled();
  });

  it("returns null when EVERY bill's bytes are missing (all skipped, no throw)", async () => {
    await seedProof({ apartmentId: APT_A, category: "utilities_tnb", storageKey: "k/gone1.pdf", filename: "a.pdf" });
    await seedProof({ apartmentId: APT_A, category: "water", storageKey: "k/gone2.png", filename: "b.png" });
    vi.mocked(fetchStorageBuffer).mockResolvedValue(null);
    const bytes = await buildProofPackPdf(ctx, OWNER, MONTH, APT_A);
    expect(bytes).toBeNull();
  });

  it("a PDF-only pack (no images) merges with NO phantom blank leading page", async () => {
    const pdf = await onePagePdf();
    await seedProof({ apartmentId: APT_A, category: "utilities_tnb", storageKey: "k/a.pdf", filename: "a.pdf" });
    await seedProof({ apartmentId: APT_A, category: "water", storageKey: "k/b.pdf", filename: "b.pdf" });
    vi.mocked(fetchStorageBuffer).mockResolvedValue(pdf);
    const bytes = await buildProofPackPdf(ctx, OWNER, MONTH, APT_A);
    expect(bytes).not.toBeNull();
    const reloaded = await PDFDocument.load(bytes!);
    // Two 1-page bills → exactly 2 pages (no empty-base phantom page).
    expect(reloaded.getPageCount()).toBe(2);
  });

  it("is BOUNDED — caps at 50 bills (the 51st is never fetched)", async () => {
    for (let i = 0; i < 51; i++) {
      await seedProof({
        apartmentId: APT_A,
        category: `c${i}`,
        storageKey: `k/p${i}.png`,
        filename: `p${i}.png`,
      });
    }
    vi.mocked(fetchStorageBuffer).mockResolvedValue(PNG_1x1);
    const bytes = await buildProofPackPdf(ctx, OWNER, MONTH, APT_A);
    expect(bytes).not.toBeNull();
    // Hard cap: only the first 50 are ever read from storage.
    expect(vi.mocked(fetchStorageBuffer).mock.calls.length).toBe(50);
    const reloaded = await PDFDocument.load(bytes!);
    expect(reloaded.getPageCount()).toBe(50);
  });
});
