import { useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, FilePlus2, FileSignature, FileText, Loader2, Plus, Save, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { RichTextEditor, type RichTextEditorHandle } from "@/components/rich-text-editor";
import { applyManagementAgreementTemplate, downloadManagementAgreement, generateManagementAgreement, getManagementAgreement, listManagementAgreementTemplates, previewManagementAgreementPdf, saveManagementAgreement, saveManagementAgreementTemplate } from "@/api/property-management-agreements";
import type { LandlordTenancyListItem } from "./landlord-tenancies-table";

type Step = "choose" | "new-template" | "edit";
const BLANK_TEMPLATE = `<div class="agreement-cover"><p>Dated on {{agreement_date}}</p><h3>BETWEEN</h3><p><strong>{{owner_name}}</strong><br>(NRIC / Company No. {{owner_id}})<br>(The Owner)</p><h3>AND</h3><p><strong>KAEN PROPERTIES MANAGEMENT SDN BHD</strong><br>(Company No. 1610050-V)<br>(The Operator)</p><h1>PROPERTY MANAGEMENT AGREEMENT</h1></div><section><h2>PROPERTY MANAGEMENT AGREEMENT</h2><p>This Agreement appoints KAEN PROPERTIES MANAGEMENT SDN BHD to manage {{property_name}}, {{property_address}} from {{commencement_date}}.</p><h2>Management Fee</h2><p>The agreed management fee is capped at RM {{management_fee_cap}} and is subject to {{sst_rate}}% SST.</p><h2>Special Conditions</h2><p>Type any special arrangements here.</p></section>`;
const FIELD_LABELS: Record<string, string> = {
  agreement_date: "Agreement date", owner_name: "Owner name", owner_id: "Owner NRIC / Company number", owner_phone: "Owner phone", owner_email: "Owner email", owner_bank_name: "Owner bank", owner_bank_account: "Owner bank account", owner_bank_holder: "Bank account holder", property_name: "Property / Condo", property_address: "Property address", commencement_date: "Commencement date", first_tenure: "First tenure", renewed_tenure: "Renewed tenure", management_fee_cap: "Management fee cap", sst_rate: "SST rate", parcel_details: "Unit / parcel / parking details",
};

export function ManagementAgreementDialog({ relation, open, onClose }: { relation: LandlordTenancyListItem; open: boolean; onClose: () => void }) {
  const qc = useQueryClient();
  const editorRef = useRef<RichTextEditorHandle>(null);
  const [step, setStep] = useState<Step>("choose");
  const [content, setContent] = useState<string | null>(null);
  const [selectedTemplate, setSelectedTemplate] = useState("");
  const [templateName, setTemplateName] = useState("");
  const [editingTemplateId, setEditingTemplateId] = useState<string | undefined>();
  const [fieldToInsert, setFieldToInsert] = useState("");
  const [previewError, setPreviewError] = useState("");
  const query = useQuery({ queryKey: ["property-management-agreement", relation.id], queryFn: () => getManagementAgreement(relation.id), enabled: open });
  const templates = useQuery({ queryKey: ["property-management-agreement-templates"], queryFn: listManagementAgreementTemplates, enabled: open });
  const draft = query.data?.draft;
  const value = content ?? draft?.contentHtml ?? "";
  const generatedVersions = query.data?.history.filter((item) => Boolean(item.fileName)) ?? [];
  const apply = useMutation({ mutationFn: (templateId: string) => applyManagementAgreementTemplate(draft!.id, templateId), onSuccess: (row) => { setContent(row.contentHtml); setStep("edit"); } });
  const save = useMutation({ mutationFn: () => saveManagementAgreement(draft!.id, value), onSuccess: () => { setContent(null); void qc.invalidateQueries({ queryKey: ["property-management-agreement", relation.id] }); } });
  const saveTemplate = useMutation({ mutationFn: () => saveManagementAgreementTemplate({ id: editingTemplateId, name: templateName.trim(), contentHtml: content ?? BLANK_TEMPLATE }), onSuccess: async (template) => { await apply.mutateAsync(template.id); setSelectedTemplate(template.id); setEditingTemplateId(undefined); void qc.invalidateQueries({ queryKey: ["property-management-agreement-templates"] }); } });
  const previewPdf = useMutation({ mutationFn: async () => { await saveManagementAgreement(draft!.id, value); return previewManagementAgreementPdf(draft!.id, value); } });
  const generate = useMutation({ mutationFn: async () => { await saveManagementAgreement(draft!.id, value); return generateManagementAgreement(draft!.id); }, onSuccess: (row) => { window.open(row.downloadUrl, "_blank", "noopener,noreferrer"); setContent(null); setStep("choose"); void qc.invalidateQueries({ queryKey: ["property-management-agreement", relation.id] }); } });
  const openPdfPreview = () => {
    setPreviewError("");
    const target = window.open("", "_blank");
    if (target) target.document.body.innerHTML = '<p style="font:16px Arial;padding:24px;color:#082B4F">Preparing Property Management Agreement preview...</p>';
    previewPdf.mutate(undefined, { onSuccess: (result) => { const bytes = Uint8Array.from(atob(result.contentBase64), (character) => character.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes], { type: "application/pdf" })); if (target) target.location.replace(url); else window.location.assign(url); window.setTimeout(() => URL.revokeObjectURL(url), 120_000); }, onError: (error) => { target?.close(); setPreviewError(error instanceof Error ? error.message : "PDF preview could not be created."); } });
  };
  if (!open) return null;
  return <div className="fixed inset-y-3 left-3 right-3 z-[120] flex overflow-hidden rounded-2xl border border-[#9DAFC1] bg-[#DDE3E9] shadow-2xl lg:left-[16rem]" role="dialog" aria-modal="true"><div className="flex h-full w-full flex-col overflow-hidden">
    <header className="flex flex-wrap items-center justify-between gap-3 border-b border-[#9DAFC1] bg-white px-5 py-3 shadow-sm"><div className="flex min-w-0 items-center gap-3"><FileSignature className="h-7 w-7 shrink-0 text-[#C9A35C]" /><div className="min-w-0"><h1 className="truncate text-xl font-bold text-[#082B4F]">Property Management Agreement</h1><p className="truncate text-sm text-[#657069]">{relation.propertyName} · {relation.landlordName}</p></div></div><Button variant="outline" onClick={onClose}>Close</Button></header>
    {query.isLoading || templates.isLoading ? <div className="grid flex-1 place-items-center"><Loader2 className="h-8 w-8 animate-spin text-[#082F55]" /></div> : <main className="min-h-0 flex-1 overflow-auto p-5">
      {step === "choose" ? <div className="mx-auto max-w-5xl space-y-5"><div><h2 className="text-2xl font-bold text-[#082B4F]">{generatedVersions.length ? "Open or create another agreement version" : "Create Property Management Agreement"}</h2><p className="mt-1 text-[#657069]">Choose a reusable template or create a new Word-style template. Owner and property details fill automatically in the preview and final PDF.</p></div>
        {draft?.contentHtml ? <section className="rounded-2xl border border-emerald-300 bg-emerald-50 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold text-emerald-950">Editable draft available</h3><p className="text-sm text-emerald-800">Continue your current wording without replacing it.</p></div><Button onClick={() => setStep("edit")}>Continue Editing Draft</Button></div></section> : null}
        <div className="grid gap-5 md:grid-cols-2"><section className="rounded-2xl border border-[#9DAFC1] bg-white p-6 shadow-sm"><FileText className="mb-3 h-8 w-8 text-[#C9A35C]" /><h3 className="text-lg font-bold text-[#082B4F]">Use existing template</h3><p className="mb-4 text-sm text-[#657069]">Keep standard clauses consistent while owner and property information fills automatically.</p><select className="h-12 w-full rounded-lg border border-[#9DAFC1] bg-white px-3" value={selectedTemplate} onChange={(event) => setSelectedTemplate(event.target.value)}><option value="">Select a template</option>{templates.data?.map((template) => <option key={template.id} value={template.id}>{template.name}{template.isDefault ? " (Default)" : ""}</option>)}</select><div className="mt-4 grid grid-cols-2 gap-2"><Button disabled={!selectedTemplate || !draft || apply.isPending} onClick={() => apply.mutate(selectedTemplate)}>Use Template</Button><Button variant="outline" disabled={!selectedTemplate} onClick={() => { const template = templates.data?.find((item) => item.id === selectedTemplate); if (!template) return; setEditingTemplateId(template.id); setTemplateName(template.name); setContent(template.contentHtml); setStep("new-template"); }}>Edit Template</Button></div></section>
        <section className="rounded-2xl border border-[#C9A35C] bg-[#FFFDF7] p-6 shadow-sm"><FilePlus2 className="mb-3 h-8 w-8 text-[#C9A35C]" /><h3 className="text-lg font-bold text-[#082B4F]">Create new template</h3><p className="mb-4 text-sm text-[#657069]">Open a blank Word-style document and save it for future owner agreements.</p><Button variant="outline" className="w-full" onClick={() => { setEditingTemplateId(undefined); setTemplateName(""); setContent(BLANK_TEMPLATE); setStep("new-template"); }}>Create New Template</Button></section></div>
        {generatedVersions.length ? <section className="rounded-2xl border border-[#9DAFC1] bg-white p-5"><h3 className="font-bold text-[#082B4F]">Generated agreement versions</h3><div className="mt-3 space-y-2">{generatedVersions.map((version) => <div key={version.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-[#DFE9F3] bg-[#F8FAFC] p-3"><div><div className="font-semibold text-[#082B4F]">Version {version.version}</div><div className="text-xs text-[#657069]">{version.fileName}</div></div><Button variant="outline" onClick={async () => { const download = await downloadManagementAgreement(version.id); window.open(download.downloadUrl, "_blank", "noopener,noreferrer"); }}><Download className="mr-2 h-4 w-4" />Download</Button></div>)}</div></section> : null}
      </div> : <div className="mx-auto max-w-[1320px] space-y-4"><div className="rounded-xl border border-[#9DAFC1] bg-white p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-[#082B4F]">{step === "new-template" ? (editingTemplateId ? "Edit Template" : "Create New Template") : "Edit Property Management Agreement"}</h2><p className="text-sm text-[#657069]">Scroll through separate letter pages, just like a Word document.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setStep("choose")}>Back</Button>{step === "new-template" ? <><input className="h-10 min-w-[270px] rounded-lg border border-[#9DAFC1] px-3" placeholder="Template name" value={templateName} onChange={(event) => setTemplateName(event.target.value)} /><Button disabled={!templateName.trim() || saveTemplate.isPending} onClick={() => saveTemplate.mutate()}><Save className="mr-2 h-4 w-4" />{editingTemplateId ? "Update Template" : "Save Template"}</Button></> : <><Button variant="outline" disabled={!draft || save.isPending} onClick={() => save.mutate()}><Save className="mr-2 h-4 w-4" />Save Draft</Button><Button variant="outline" disabled={!draft || previewPdf.isPending} onClick={openPdfPreview}>{previewPdf.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <FileText className="mr-2 h-4 w-4" />}Preview PDF</Button><Button disabled={!draft || generate.isPending} onClick={() => generate.mutate()}><Download className="mr-2 h-4 w-4" />Generate & Download PDF</Button></>}</div></div>{previewError ? <p className="mt-3 rounded-lg border border-red-300 bg-red-50 px-3 py-2 text-sm font-medium text-red-700">{previewError}</p> : null}</div>
        <div className="grid min-h-0 gap-4 xl:grid-cols-[280px_minmax(0,1fr)]"><aside className="space-y-4 xl:sticky xl:top-0 xl:max-h-[72vh] xl:overflow-auto"><section className="rounded-xl border border-[#9DAFC1] bg-white p-4"><h3 className="flex items-center gap-2 font-bold text-[#082B4F]"><Sparkles className="h-4 w-4 text-[#C9A35C]" />Automatic details</h3><p className="mt-1 text-xs leading-5 text-[#657069]">Select a field and insert it at your cursor. The final document replaces it with the latest owner or property information.</p><select className="mt-3 h-10 w-full rounded-md border border-[#9DAFC1] bg-white px-2 text-sm" value={fieldToInsert} onChange={(event) => setFieldToInsert(event.target.value)}><option value="">Choose a field</option>{Object.entries(FIELD_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><Button type="button" variant="outline" className="mt-2 w-full" disabled={!fieldToInsert} onClick={() => editorRef.current?.insertHtml(`<span data-field="${fieldToInsert}">{{${fieldToInsert}}}</span>&nbsp;`)}><Plus className="mr-2 h-4 w-4" />Insert at cursor</Button><div className="mt-3 space-y-2">{Object.entries(FIELD_LABELS).map(([key, label]) => <div key={key} className="rounded-lg border border-[#DFE9F3] bg-[#F8FAFC] p-2"><span className="block text-xs font-bold text-[#082B4F]">{label}</span><span className="block text-xs text-[#657069]">Automatic field</span></div>)}</div></section></aside>
        <RichTextEditor ref={editorRef} value={value} onChange={setContent} minHeight={1056} pageMode fieldValues={Object.fromEntries(Object.entries(FIELD_LABELS).map(([key, label]) => [key, `[${label}]`]))} fieldLabels={FIELD_LABELS} ariaLabel={step === "new-template" ? "Property management agreement template editor" : "Property management agreement editor"} /></div>
      </div>}
    </main>}
  </div></div>;
}
